# Generated by Django 3.2 on 2021-10-15 15:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='Create_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
